services:
    siesc_data.listener.docente:
        class: Siesc\DataBundle\EventListener\DocenteListener
        tags:
            - { name: kernel.event_listener, event: siesc.docente.pre_create, method: onPreCreate }


