siesc_docente_new: 
    path:     /new
    defaults: { _controller: SiescAdminBundle:Docente:new }
    
siesc_docente_show:  
    path:     /{id}/show
    defaults: { _controller: SiescAdminBundle:Docente:show }
    
siesc_docente_edit: 
    path:     /{id}/edit
    defaults: { _controller: SiescAdminBundle:Docente:edit }
    
siesc_docente_delete:
    path:    /{id}/delete
    defaults: { _controller: SiescAdminBundle:Docente:delete }