parameters:
#    siesc_academico.example.class: Siesc\AcademicoBundle\Example

services:
#    siesc_academico.example:
#        class: %siesc_academico.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
